import "./globals.css"; 
import Footer from "@/components/Footer";
import Header from "@/components/Header";



export const metadata = {

  title: "trouve ton artisan",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  }
};

export default function RootLayout({ children }) {


  return (
    <html lang="fr">
      
      <body>
    
      <Header />
      <main className="min-h-screen flex flex-col py-5">
       {children}
      </main>
      <Footer />
      </body>
    </html>
  );
}
